[workspace]
resolver = "2"
members = [
    "./packages/fft",
    "./packages/lyric",
    "./packages/ws-protocol",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3
codegen-units = 1
lto = true
panic = "abort"

