[package]
name = "lyric"
version = "0.0.2"
authors = ["SteveXMH <39523898+Steve-xmh@users.noreply.github.com>"]
edition = "2021"
repository = "https://github.com/Steve-xmh/applemusic-like-lyrics"
description = "一个歌词解析/生成模块，着重于歌词内容解析，支持多种格式"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "qrc"]
qrc = ["dep:cipher", "cipher/zeroize"]

[dependencies]
wasm-bindgen = "0.2.63"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }
nom = "7.1.3"
js-sys = "0.3.64"
serde = { version = "1.0.166", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
cipher = { version = "0.4.4", optional = true }
miniz_oxide = "0.7.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[build-dependencies]
cc = "1.0.82"
